### ISSUE TITLE
Provisioning fails, possibly during database migration phase and/or nosetests

### ISSUE THREAD

**Issue by brucecrevensten** [liip/ckan-vagrant#2]
First: thanks for your great work on this!

When executing `vagrant up` (Vagrant version 1.6.5, host OS OSX 10.8.5) the provisioning errors out.  I think the relevant log dump is here (snipped at the end with some recurring errors).

```
==> default: migrate.versioning.repository: DEBUG: Config: OrderedDict([('db_settings', OrderedDict([('__name__', 'db_settings'), ('repository_id', 'Ckan'), ('version_table', 'migrate_version'), ('required_dbs', '[]')]))])
==> default: migrate.versioning.util: DEBUG: Disposing SQLAlchemy engine Engine(postgresql://ckan_default:pass@localhost/ckan_test)
==> default: ckan.model: INFO: CKAN database version upgraded: 0 -> 71
==> default: ckan.lib.activity_streams_session_extension: DEBUG: session had no _object_cache or no revision, skipping this commit
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/ckan/lib/activity_streams_session_extension.py", line 52, in before_commit
==> default:     revision = session.revision
==> default: AttributeError: 'SessionMaker' object has no attribute 'revision'
==> default: ckan.lib.activity_streams_session_extension: DEBUG: session had no _object_cache or no revision, skipping this commit
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/ckan/lib/activity_streams_session_extension.py", line 52, in before_commit
==> default:     revision = session.revision
==> default: AttributeError: 'SessionMaker' object has no attribute 'revision'
==> default: ckan.lib.activity_streams_session_extension: DEBUG: session had no _object_cache or no revision, skipping this commit
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/ckan/lib/activity_streams_session_extension.py", line 51, in before_commit
==> default:     object_cache = session._object_cache
==> default: AttributeError: 'SessionMaker' object has no attribute '_object_cache'
==> default: ckan.model: INFO: Database initialised
==> default: --------------------- >> end captured logging << ---------------------
==> default: 
==> default: ======================================================================
==> default: ERROR: Failure: AttributeError ('module' object has no attribute 'model')
==> default: ----------------------------------------------------------------------
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
==> default:     addr.filename, addr.module)
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
==> default:     return self.importFromDir(dir_path, fqname)
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
==> default:     mod = load_module(part_fqname, fh, filename, desc)
==> default:   File "/home/vagrant/pyenv/src/ckan/ckan/lib/create_test_data.py", line 5, in <module>
==> default:     import ckan.model as model
==> default: AttributeError: 'module' object has no attribute 'model'
==> default: 
==> default: ======================================================================
==> default: ERROR: Failure: AttributeError ('module' object has no attribute 'model')
==> default: ----------------------------------------------------------------------
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
==> default:     addr.filename, addr.module)
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
==> default:     return self.importFromDir(dir_path, fqname)
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/importer.py", line 92, in importFromDir
==> default:     mod = load_module(part_fqname, fh, filename, desc)
==> default:   File "/home/vagrant/pyenv/src/ckan/ckan/logic/__init__.py", line 8, in <module>
==> default:     import ckan.model as model
==> default: AttributeError: 'module' object has no attribute 'model'
==> default: 
==> default: ======================================================================
==> default: ERROR: Failure: AttributeError ('module' object has no attribute 'new_authz')
==> default: ----------------------------------------------------------------------
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
==> default:     addr.filename, addr.module)
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
==> default:     return self.importFromDir(dir_path, fqname)
==> default:   File "/home/vagrant/pyenv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
==> default:     mod = load_module(part_fqname, fh, filename, desc)
==> default:   File "/home/vagrant/pyenv/src/ckan/ckan/new_tests/lib/navl/test_validators.py", line 9, in <module>
==> default:     import ckan.new_tests.factories as factories
==> default:   File "/home/vagrant/pyenv/src/ckan/ckan/new_tests/factories.py", line 43, in <module>
==> default:     import ckan.logic
==> default:   File "/home/vagrant/pyenv/src/ckan/ckan/logic/__init__.py", line 9, in <module>
==> default:     import ckan.new_authz as new_authz
==> default: AttributeError: 'module' object has no attribute 'new_authz'
```

Not sure where to proceed from here.  Am I missing something in my host environment or other spots?

**Comment by tschortsch** [comment]
Should be fixed in commit b7b174286378aae4f7655c6cf567e88e4065f116.
